var myString;
var myNum;
var myBool;
var myVar;
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = 'Hello'.slice(0, 3);
myNum = 1;
myBool = true;
myVar = 5;
strArr = ['Hello', 'World'];
numArr = [1, 2, 3];
boolArr = [true, false, true];
strNumTuple = ['Hello', 4];
var myVoid = undefined;
var myNull = null;
var myUndefined = undefined;
console.log(myVoid);
